# Generated by Django 4.2.11 on 2024-03-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vitenamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=255)),
                ('trigger_similarity_0', models.FloatField(blank=True, null=True)),
                ('trigger_similarity_1', models.FloatField(blank=True, null=True)),
                ('det_0', models.JSONField(blank=True, null=True)),
                ('det_1', models.JSONField(blank=True, null=True)),
                ('proc_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
